# config_gecco.py

# --- PARAMETRI SPAZIALI (PITCH CONTROL & xT) ---
GRID_RES = 50           
PLAYER_INFLUENCE_R = 0.15 
EPSILON = 1e-5          

LAMBDA_GHOSTING = 3.5 

# --- VINCOLI ---
FIELD_LIMITS = (1.0, 1.0)
GOALKEEPER_AREA = {
    "x_min": 0.0, "x_max": 0.165,
    "y_min": 0.21, "y_max": 0.79
}
MIN_DIST_PLAYER = 0.10 

# --- PESI DELLE PENALITÀ ---
PENALTY_W_BOUNDARY   = 10.0    
PENALTY_W_GOALKEEPER = 10.0    
PENALTY_W_PROXIMITY  = 50.0
PENALTY_W_BALL       = 150.0
PENALTY_W_OFFSIDE    = 200.0

# --- PESI TATTICI ---
WEIGHT_TACTICAL_ATTACK = 20.0   
WEIGHT_REST_DEFENSE    = 20.0    
WEIGHT_TACTICAL_DEFEND = 20.0